### PR TITLE
Russian language fix

### PR DESCRIPTION
**Pull request by Romz24**

### CODE REVIEW

**Comment by Paliverse** [comment]
This is not really the best place to update the language, it's better through Loclazy so its up to date for everyone.

**Comment by Paliverse** [comment]
i will have to manually update each one from the ones you updated.

**Comment by Paliverse** [comment]
have updated the changes in Localazy. will close this request.

**Comment by Romz24** [comment]
Can you tell me more about this?

**Comment by Paliverse** [comment]
If you go to 

* https://localazy.com/p/dualsensex

you can update keys here easily, it’s what’s recommended to translate languages.

**Comment by Romz24** [comment]
Thanks. I see you have already ported my changes to Localazy. If I still find inaccuracies in the translation, I will definitely add them there right away.

**Pull request closed without merging**
