### PR TITLE
Add DualSenseAT at README

### PR DESCRIPTION
**Pull request by josealissonbr**
DualSenseAT is an application that uses the Adaptive Triggers system that DualSenseX provides, making it possible to use the Adaptive Triggers feature in various PC games.

### CODE REVIEW

**Comment by Paliverse** [comment]
Sorry but I don’t understand what this is about. What is DualSenseAT app?

**Comment by josealissonbr** [comment]
DualSenseAT makes games that are not compatible with Adaptive Triggers compatible, apenas com poucas linhas em C#.

**Comment by josealissonbr** [comment]
Utilizando o seu sistema de TXT.

**Comment by josealissonbr** [comment]
You can check the source code of the App, to understand how it works.

**Comment by josealissonbr** [comment]
I started this repository today, so give me a discount on organization and structure.

**Pull request closed without merging**
