### PR TITLE
Update _DualSenseXVersionNumber.txt

### PR DESCRIPTION
**Pull request by DanielSvoboda**
Fix the version number that prevents the program from updating!
The current version of the assembly is 1.4.9, when you start the program it will check this file: 1.5.0 and it will start an infinite update loop.
Correct this file, or send the version 1.5.0 files

### CODE REVIEW

**Comment by Paliverse** [comment]
This is done on purpose to alert users of the steam version.

**Comment by eondiscord** [comment]
in my opinion continuing the program as closed source and bombarding users to pay for the new version was the wrong thing to do

**Comment by Paliverse** [comment]
> in my opinion continuing the program as closed source and bombarding users to pay for the new version was the wrong thing to do

Check the files on here, it's not open sourced. Only hosted on Github.

**Comment by AlakbarovAyxan** [comment]
I can't see my battery status on my ps5 remote

**Pull request closed without merging**
